#ifndef COMMONVALS
#define COMMONVALS
#include "stb_image.h"

const int MAX_POINT_LIGHTS = 4;
const int MAX_SPOT_LIGHTS = 4; // LA SUMA DEBE SER ENTRE DOS Y SIETE UY DEBE DE HABER POR LO MENOS UNA Y UNA //PARA EL EJERCIIO Y EL REPORTE SE USA MAS SPOTLIGHT 

// LA OCTAVA LUZ ES LA LUZ DIRECCIONAL
#endif